[package]
name = "meal_planner"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite"] }
text_io = "0.1.12"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
